# Change these first
owner: theweezar # GitHub username
repo: upptime-demo # GitHub repository name
sites: # List of endpoints to track
  - name: Youtube
    url: https://www.youtube.com/
status-website: # Status website (optional)
  baseUrl: /upptime-demo
  name: Upptime # Status website title